name: Deploy Backend to Napoleon Host

on:
  push:
    branches: [main]
    paths:
      - 'backend/**' # Só roda o deploy se houver alterações na pasta backend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install Dependencies & Build
        working-directory: ./backend
        run: |
          npm ci
          npm run build

      - name: Deploy to Server via SFTP/SSH
        uses: easingthemes/ssh-deploy@v3
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO --delete --exclude='.git*' --exclude='node_modules' --exclude='.env' --exclude='prisma/dev.db'"
          SOURCE: 'backend/'
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USERNAME }}
          TARGET: '/home/devcaioe/api.devcaioeduardo.com.br/'

      - name: Restart Node.js Application & Migrate
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/devcaioe/api.devcaioeduardo.com.br
            /home/devcaioe/nodevenv/api.devcaioeduardo.com.br/20/bin/npm install --production
            /home/devcaioe/nodevenv/api.devcaioeduardo.com.br/20/bin/npx prisma migrate deploy
            mkdir -p tmp
            touch tmp/restart.txt
